"modality": "rna+adt"
"spl_pct": .01
"train": {"n_seeds": 1, "test_mode": True}
"eval": {"k_array": [5, 10, 15, 20, 35, 50],
         "resolutions": [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9,],
         "k_cnct": [3, 5, 10, 15],
         "n_subsamples": null} #20000}
"remove_data": False

"baseline_cfgs": {#"Uniport": {"seeds": [37, 24, 369, 713, 48], "rm_data": True, "no_mix": False, "tr_length": 30000},
                  "MultiMAP": {"seeds": [37, 24, 369, 713, 48], "rm_data": True},
                  #"scGLUE": {"seeds": [37, 24, 369, 713, 48], "rm_data": True, "cpu_only": False, "tr_length": "AUTO", "latent_dim": 15},
                  "Seurat": {"seeds": [37], "rm_data": True, "n_latent": null},
                  #"Liger": {"seeds": [37, 24, 369, 713, 48], "rm_data": True, "n_latent": null}
}

"data": {"subsample_seed": 42,
         "paired": True,
         "rna": {
           "QC": { "min_cells_ratio": 0.0001, "max_cells_ratio": 1., "min_features": 0, "max_features": 200000 },
           "normalization": { "target_sum": 10000. },
           "feature_selection": { "raw": { "n_top_features": 3000 },
                                  "normalized": { "n_top_features": 3000 } },
           "n_pca": 100},
           "adt": {
             "QC": { "min_cells_ratio": 0.005, "max_cells_ratio": 0.99, "min_features": 0, "max_features": 200000 },
             "normalization": { "csr": True },
             "n_pca": null },

           "cross_rel": { "rna+adt": { "common_features": { "gene_prot_names": { 'CD11a': 'ITGAL', 'CD11c': 'ITGAX', 'CD123': 'IL3RA', 'CD14': 'CD14', 'CD16': 'FCGR3A',
                                                                                 'CD161': 'KLRB1', 'CD19': 'CD19', 'CD25': 'IL2RA', 'CD27': 'CD27', 'CD28': 'CD28',
                                                                                 'CD3': 'CD3G', 'CD38': 'CD38', 'CD4': 'CD4', 'CD45RA': 'PTPRC', 'CD45RO': 'PTPRC',
                                                                                 'CD56': 'NCAM1', 'CD69': 'CD69', 'CD79b': 'CD79B', 'CD86': 'CD86', 'CD47': 'CD47',
                                                                                 'CD48': 'CD48', 'CD40': 'CD40', 'CD52': 'CD52', 'CD33': 'CD33', 'CD7': 'CD7',
                                                                                 'CD44': 'CD44', 'TIGIT': 'TIGIT', 'CD5': 'CD5', 'KLRG1': 'KLRG1', 'CD1c': 'CD1C',
                                                                                 'CD1d': 'CD1D', 'CD58': 'CD58', 'CX3CR1': 'CX3CR1', 'CD24': 'CD24', 'CD244': 'CD244',
                                                                                 'CD163': 'CD163', 'CD83': 'CD83', 'CD2': 'CD2', 'CD226': 'CD226', 'CD81': 'CD81',
                                                                                 'CD22': 'CD22', 'CD63': 'CD63', 'CD36': 'CD36', 'CD72': 'CD72', 'CD93': 'CD93',
                                                                                 'CD9': 'CD9', 'HLA-E': 'HLA-E', 'CD82': 'CD82', 'CD101': 'CD101', 'CD11b': 'ITGAM',
                                                                                 'CD127': 'IL7R', 'CD141': 'THBD', 'CD172a': 'SIRPA', 'CD185': 'CXCR5', 'CD21': 'CR2',
                                                                                 'CD278': 'ICOS', 'CD304': 'NRP1', 'CD319': 'SLAMF7', 'CD39': 'ENTPD1',
                                                                                 'HLA-DR': 'HLA-DRA', 'IgD': 'IGHD', 'IgM': 'IGHM', 'CD192': 'CCR2', 'CD71': 'TFRC',
                                                                                 'CD95': 'FAS', 'CD270': 'TNFRSF14', 'CD155': 'PVR', 'CD112': 'NECTIN2',
                                                                                 'CD154': 'CD40LG', 'CD8': 'CD8A', 'HLA-A-B-C': [ 'HLA-A', 'HLA-B', 'HLA-C' ],
                                                                                 'CD105': 'ENG', 'CD49f': 'ITGA6', 'CD194': 'CCR4', 'CD20': 'MS4A1', 'CD335': 'NCR1',
                                                                                 'CD31': 'PECAM1', 'CD195': 'CCR5', 'CD32': 'FCGR2A', 'CD196': 'CCR6', 'CD103': 'ITGAE',
                                                                                 'CD62L': 'SELL', 'CD152': 'CTLA4', 'CD223': 'LAG3', 'CD107a': 'LAMP1',
                                                                                 'CD134': 'TNFRSF4', 'CD64': 'FCGR1A', 'CD314': 'KLRK1', 'CD35': 'CR1', 'CD272': 'BTLA',
                                                                                 'integrinB7': 'ITGB7', 'CD268': 'TNFRSF13C', 'CD42b': 'GP1BA', 'CD54': 'ICAM1',
                                                                                 'CD119': 'IFNGR1', 'CD122': 'IL2RB', 'FceRIa': 'FCER1A', 'CD137': 'TNFRSF9',
                                                                                 'CD124': 'IL4R', 'CD13': 'ANPEP', 'CD29': 'ITGB1', 'CD18': 'ITGB2', 'CD45': 'PTPRC',
                                                                                 'CD26': 'DPP4', 'CD115': 'CSF1R', 'CD49a': 'ITGA1', 'CD49d': 'ITGA4', 'CD73': 'NT5E',
                                                                                 'CD352': 'SLAMF6', 'CD94': 'KLRD1', 'CD162': 'SELPLG', 'CD85j': 'LILRB1',
                                                                                 'CD23': 'FCER2', 'CD328': 'SIGLEC7', 'CD88': 'C5AR1', 'CD303': 'CLEC4C', 'TCR': 'TRAC' } },
                                       "prepro": { "rna": { "norm_method": "log_norm", "norm_params": { "target_sum": 10000. },
                                                            "hvg": { }, "scale": True, "scale_params": { } },
                                                   "adt": { "norm_method": "clr", "norm_params": { },
                                                            "hvg": { }, "scale": True, "scale_params": { } } } } }}

"model":  { # null means using data.X so normalized data
    "input_choice": { "rna": { "hvg_only": True,
                               "rep_in": "X_pca", "rep_out": "counts" },
                      "adt": { "hvg_only": False,
                                "rep_in": null, "rep_out": null } },
    "model": { "mmae_args": { "mass": 0.5,
                              "reach": 0.3,
                              "blur": 0.01,
                              "iot_loss_weight": 0.01,
                              "sinkhorn_loss_weight": 0.1 },
               "n_hidden": null,
               "n_latent": 16,
               "impute": False,
               "monitor_mix_entr": False,
               "rna": { "n_hidden": 64,
                        "avg_feat": True,
                        "var_eps": 0.0001,
                        "n_layers_enc": 3,
                        "type_loss": "zinb",
                        "dropout_rate": 0.,
                        "use_batch_norm_enc": null,
                        "use_batch_norm_dec": null,
                        "deeply_inject_covariates_dec": True,
               },
               "adt": { "n_hidden": 32,
                        "type_loss": "l2",
                        "avg_feat": True,
                        "n_layers_enc": 3,
                        "var_eps": 0.0001,
                        "dropout_rate": 0.,
                        "use_batch_norm_enc": null,
                        "use_batch_norm_dec": null,
                        "deeply_inject_covariates_dec": True,
               } },
    "train": { "max_epochs": 10000,
               "batch_size": 512,
               "ratio_val": 0.2,
               "pin_memory": True,
               "num_workers": 0,
               "use_cuda": True,
               "lr": 0.003,
               "early_stopping": True,
               "patience": 40,
               "es_metric": "val_full_loss",
               "log_every_n_steps": 40,
               "detect_anomaly": False,
               "track_grad_norm": -1, },
    "second": null
}