"modality": "rna+atac+adt"
"spl_pct": .01
"train": {"n_seeds": 1, "test_mode": True}
"remove_data": False


"data": {"subsample_seed": 42,
         "paired": False,
           "rna": {
             "QC": { "min_cells_ratio": 0., "max_cells_ratio": 1., "min_features": 100, "max_features": 20000 },
             "normalization": { "target_sum": 10000. },
             "feature_selection": { "raw": { "n_top_features": 3000 },
                                    "normalized": { "n_top_features": 3000 } },
             "n_pca": 100},
           "atac": {
             "QC": { "min_cells_ratio": 0.005, "max_cells_ratio": 0.99, "min_features": 100, "max_features": 100000 },
             "normalization": { "log_tf": True, "log_idf": True, "log_tfidf": False, "scale_factor": 10000.0 },
             "feature_selection": { "raw": { "n_top_features": 3000 },
                                    "normalized": { "n_top_features": 3000 },
                                    "n_gene_act_hvg": 1000 },
             "n_pca": 100},
           "adt": {
             "QC": { "min_cells_ratio": 0.005, "max_cells_ratio": 0.99, "min_features": 0, "max_features": 200000 },
             "normalization": { "csr": True },
             "n_pca": null },

           "cross_rel": { "rna+atac": { "common_features": { "atac_key": "gene_activities_norm" },
                                        "prepro": { "rna": { "norm_method": "log_norm", "norm_params": { "target_sum": 10000. },
                                                             "hvg": { "n_top_genes": 3000, "flavor": "seurat" },
                                                             "scale": False, "scale_params": { } },
                                                    "atac": { "norm_method": null, "norm_params": { },
                                                              "hvg": { }, "scale": False, "scale_params": { } } } },
                          "rna+adt": { "common_features": { "gene_prot_names": { 'IgG': 'IGHG1', 'HLA_DR': 'HLA-DRA',
                                                                                 'Siglec_8': 'SIGLEC8', 'Ki_67': 'MKI67',
                                                                                 'PD1': 'PDCD1', 'CD57': 'B3GAT1', 'BCL_2': 'BCL2', 'Vd2': 'TRDV2', 'IgA': 'IGHA1',
                                                                                 'CD66': 'CEACAM1', 'KLGR1': 'KLRG1', 'CLA': 'SELPLG', 'GZB': 'GZMB', 'CD16': 'FCGR3A',
                                                                                 'CD19': 'CD19', 'CD3': 'CD3G', 'CD4': 'CD4', 'CD28': 'CD28', 'CD56': 'NCAM1',
                                                                                 'CD127': 'IL7R', 'CD103': 'ITGAE', 'CD161': 'KLRB1', 'CD27': 'CD27', 'CD14': 'CD14',
                                                                                 'CD45RO': 'PTPRC', 'CD39': 'ENTPD1', 'CD45RA': 'PTPRC', 'CD33': 'CD33', 'CD69': 'CD69',
                                                                                 'CD11c': 'ITGAX', 'IgM': 'IGHM', 'CD8': 'CD8A', 'CD20': 'MS4A1', 'CD38': 'CD38',
                                                                                 'CD45': 'PTPRC', 'CD123': 'IL3RA', 'CD25': 'IL2RA', 'CD141': 'THBD', 'CX3CR1': 'CX3CR1',
                                                                                 'CTLA4': 'CTLA4', 'CCR7': 'CCR7', 'CD99': 'CD99', 'FOXP3': 'FOXP3' } },
                                       "prepro": { "rna": { "norm_method": null, "norm_params": { },
                                                            "hvg": { }, "scale": True, "scale_params": { } },
                                                   "adt": { "norm_method": null, "norm_params": { },
                                                            "hvg": { }, "scale": True, "scale_params": { } } } },
                          "atac+adt": { "common_features": { "atac_key": "gene_activities_norm",
                                                             "gene_prot_names": { 'HLA_DR': 'HLA-DRA', 'Siglec_8': 'SIGLEC8',
                                                                                  'Ki_67': 'MKI67', 'PD1': 'PDCD1', 'CD57': 'B3GAT1',
                                                                                  'BCL_2': 'BCL2', 'CD66': 'CEACAM1', 'KLGR1': 'KLRG1',
                                                                                  'CLA': 'SELPLG', 'GZB': 'GZMB', 'CD99': 'CD99L2',
                                                                                  'CD16': 'FCGR3A', 'CD19': 'CD19', 'CD3': 'CD3G',
                                                                                  'CD4': 'CD4', 'CD28': 'CD28', 'CD56': 'NCAM1',
                                                                                  'CD127': 'IL7R', 'CD103': 'ITGAE', 'CD161': 'KLRB1',
                                                                                  'CD27': 'CD27', 'CD14': 'CD14', 'CD45RO': 'PTPRC',
                                                                                  'CD39': 'ENTPD2', 'CD45RA': 'PTPRC', 'CD33': 'CD33',
                                                                                  'CD69': 'CD69', 'CD11c': 'ITGAX', 'CD8': 'CD8A',
                                                                                  'CD20': 'MS4A1', 'CD38': 'CD38', 'CD45': 'PTPRC',
                                                                                  'CD123': 'IL3', 'CD25': 'IL2RA', 'CD141': 'THBD',
                                                                                  'CX3CR1': 'CX3CR1', 'CTLA4': 'CTLA4', 'CCR7': 'CCR7',
                                                                                  'FOXP3': 'FOXP3' } },
                                        "prepro": { "atac": { "norm_method": null, "norm_params": { },
                                                              "hvg": { }, "scale": False, "scale_params": { } },
                                                    "adt": { "norm_method": null, "norm_params": { },
                                                             "hvg": { }, "scale": False, "scale_params": { } } } }}}

"model":  { # null means using data.X so normalized data
    "input_choice": { "rna": { "hvg_only": True,
                               "rep_in": "X_pca", "rep_out": "counts" },
                      "atac": { "hvg_only": False,
                                "rep_in": "X_pca", "rep_out": null },
                      "adt": { "hvg_only": False,
                                "rep_in": null, "rep_out": null }
    },
    "model": { "mmae_args": { "mass": 0.5,
                              "reach": 0.3,
                              "blur": 0.01,
                              "iot_loss_weight": 0.01,
                              "sinkhorn_loss_weight": 0.03 },
               "n_hidden": null,
               "n_latent": 16,
               "impute": False,
               "monitor_mix_entr": False,
               "rna": { "n_hidden": 64,
                        "avg_feat": True,
                        "var_eps": 0.0001,
                        "n_layers_enc": 3,
                        "type_loss": "zinb",
                        "dropout_rate": 0.,
                        "use_batch_norm_enc": null,
                        "use_batch_norm_dec": null,
                        "deeply_inject_covariates_dec": True,
               },
               "atac": { "n_hidden": 64,
                         "reconstruction_weight": 5.,
                         "var_eps": 0.0001,
                         "n_layers_enc": 3,
                         "dropout_rate": 0.,
                         "use_batch_norm_enc": null,
                         "use_batch_norm_dec": null,
                         "avg_feat": True,
                         "type_loss": "l2",
                         "deeply_inject_covariates_dec": True,
               },
               "adt": { "n_hidden": 32,
                        "type_loss": "l2",
                        "avg_feat": True,
                        "n_layers_enc": 3,
                        "var_eps": 0.0001,
                        "dropout_rate": 0.,
                        "use_batch_norm_enc": null,
                        "use_batch_norm_dec": null,
                        "deeply_inject_covariates_dec": True,
               }
    },
    "train": { "max_epochs": 10000,
               "batch_size": 1256,
               "ratio_val": 0.2,
               "pin_memory": True,
               "num_workers": 0,
               "use_cuda": True,
               "lr": 0.003,
               "early_stopping": True,
               "patience": 40,
               "es_metric": "val_full_loss",
               "log_every_n_steps": 40,
               "detect_anomaly": False,
               "track_grad_norm": -1, },
    "second": null
}